# Generated by Django 5.2.5 on 2025-08-16 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendancerecord',
            name='check_in',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
