# Generated by Django 4.2.7 on 2025-08-20 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ems_api', '0002_alter_attendancerecord_check_in'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='TaskProgressUpdate',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('previous_progress', models.IntegerField()),
                ('new_progress', models.IntegerField()),
                ('previous_status', models.CharField(max_length=15)),
                ('new_status', models.CharField(max_length=15)),
                ('update_notes', models.TextField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_updates', to='ems_api.task')),
                ('updated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_updates', to='ems_api.employee')),
            ],
            options={
                'db_table': 'task_progress_updates',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_name', models.CharField(max_length=255)),
                ('file_path', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='ems_api.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_files', to='ems_api.employee')),
            ],
            options={
                'db_table': 'task_attachments',
            },
        ),
    ]
