# Generated by Django 5.2.5 on 2025-08-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_api', '0003_task_last_updated_taskprogressupdate_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
    ]
