# Generated by Django 4.2.7 on 2025-08-21 19:19

import datetime
from django.db import migrations, models
import ems_api.models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_api', '0004_employee_age_employee_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='hire_date',
        ),
        migrations.AddField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(default=datetime.date(2020, 1, 1), help_text='Date when the employee joined the company', validators=[ems_api.models.validate_joining_date]),
        ),
        migrations.AlterField(
            model_name='employee',
            name='age',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True, validators=[ems_api.models.validate_date_of_birth]),
        ),
    ]
