# Generated by Django 4.2.7 on 2025-08-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ems_api', '0005_remove_employee_hire_date_employee_joining_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='date_of_birth',
            field=models.DateField(blank=True, help_text='Format: YYYY-MM-DD', null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='joining_date',
            field=models.DateField(help_text='Date when the employee joined the company'),
        ),
    ]
